### ISSUE TITLE
Signature not valid

### ISSUE THREAD

**Issue by ghost** [hiyali/go-lib-ssv#1]

**Comment by hiyali** [comment]
Sure, you could give the callback URL.

**Comment by CodeyChecks** [comment]
Code I'm using. I'm running this on a local environment. 
`go run main.go`
Output: 2019/12/30 08:19:50 Signature not valid

```
package main

import (
	"go-lib-ssv/admob"
	"log"
	"net/url"
)

func main() {
  admob.LogEnabled = true // enable log query raw, default is: false
    u, err := url.Parse("https://testing.com/reward.php?ad_network=5450213213286189855&signature=MEYCIQDrVz1G9OUCHGf0kmckCx5pnaeNQul6XVYeSydJYAF3bwIhALcEy2JQQV7s9iMBzIk6oN8io72Y6lCqzQS1jMkN2QV2&key_id=3335741209")
	if err != nil {
		log.Fatal(err)
	}
  if err := admob.Verify(u); err != nil {
  	log.Print(err)
  	return;
  }

  // Verified

  log.Print("verified!!!")
}
```

**Comment by CodeyChecks** [comment]
What is wrong? I tried multiple different valid signatures with the key_id from the callbacks.

**Comment by CodeyChecks** [comment]
@hiyali I got it working now, I did not realize full URL must be provided.

I have a question, I reward my user after verification. It seems like users are still able to cheat fake requests with valid signatures. How is this possible?

**Comment by hiyali** [comment]
@CodeyChecks You must save `order_id ` (or `transaction_id` or something like this) to avoid verify and reward twice.

Good luck.

**Comment by CodeyChecks** [comment]
@hiyali THANK YOU!! I have been trying to figure it out all day!

The hackers were using a replay attack!
