### ISSUE TITLE
Signature not valid

### ISSUE THREAD

**Issue by marklonquist** [hiyali/go-lib-ssv#2]
Hi!

I'm passing this URL into the verifier;
`/go-api/v1.0/meta/callbacks/admob/2?ad_network=4970775877303683148&ad_unit=1000666186&reward_amount=1&reward_item=Key%20Doubler&timestamp=1584354656623&transaction_id=19808b2d2660df761d5a3259a3d6fbc6&user_id=GbgZbUuAyUgbyTZYQUA2eGNLsjh1&signature=MEUCIBAEW1jAC72wybEVSeexWF4LESQ7Nkoypy3y1swVDAUvAiEAhKsB68Myzr0N3_dEHFTeeRRlFYFkmyPGW6I5hSEkIGw&key_id=3335741209`

But we always get a "Signature not valid" error. Can't seem to understand why though.

// Mark

**Comment by marklonquist** [comment]
ok, seems I found the issue. Apparantly if you have spaces in the reward_item, eg.: "Key%20Doubler" = "Key Doubler", the validation fails.

Changed our reward_items to use "-" rather than a space

**Comment by hiyali** [comment]
@marklonquist Thanks for the feedback, which could save the time of others.

**Comment by marklonquist** [comment]
@hiyali I made a pull request to fix it :-)
