### ISSUE TITLE
AdMob SSV in Php

### ISSUE THREAD

**Issue by Obnotname** [hiyali/go-lib-ssv#5]
Hi,

I would like to use AdMobs SSV in Php, I've already found a lib for Go and Python, however I need it for Php and there is none unfortunetly https://developers.google.com/admob/android/rewarded-video-ssv

Might you explain your steps, so that I can rebuild in Php?

Thanks in advance!

**Comment by hiyali** [comment]
Hey, @Obnotname.

I have no time to explain line by line this lib to you.

You may write Admob SSV lib in PHP, based on other same libs in other languages. I think this thing may take your time as one day around.

Good luck.
